// Class: ReadCuts
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : Cuts::Cuts
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.04/16       [394256]
Creator        : btong
Date           : Tue Feb 21 22:29:09 2017
Host           : Linux lcgapp-slc6-physical1.cern.ch 2.6.32-573.8.1.el6.x86_64 #1 SMP Wed Nov 11 15:27:45 CET 2015 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/work/b/btong/bbbb/MoriondAnalysis/MakePlot
Training events: 4674
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
FitMethod: "MC" [Minimisation Method (GA, SA, and MC are the primary methods to be used; the others have been introduced for testing purposes and are depreciated)]
EffMethod: "EffSel" [Selection Method]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
CutRangeMin[0]: "-1.000000e+00" [Minimum of allowed cut range (set per variable)]
    CutRangeMin[1]: "-1.000000e+00"
    CutRangeMin[2]: "-1.000000e+00"
    CutRangeMin[3]: "-1.000000e+00"
    CutRangeMin[4]: "-1.000000e+00"
    CutRangeMin[5]: "-1.000000e+00"
    CutRangeMin[6]: "-1.000000e+00"
    CutRangeMin[7]: "-1.000000e+00"
    CutRangeMin[8]: "-1.000000e+00"
    CutRangeMin[9]: "-1.000000e+00"
    CutRangeMin[10]: "-1.000000e+00"
    CutRangeMin[11]: "-1.000000e+00"
    CutRangeMin[12]: "-1.000000e+00"
    CutRangeMin[13]: "-1.000000e+00"
    CutRangeMin[14]: "-1.000000e+00"
    CutRangeMin[15]: "-1.000000e+00"
    CutRangeMin[16]: "-1.000000e+00"
CutRangeMax[0]: "-1.000000e+00" [Maximum of allowed cut range (set per variable)]
    CutRangeMax[1]: "-1.000000e+00"
    CutRangeMax[2]: "-1.000000e+00"
    CutRangeMax[3]: "-1.000000e+00"
    CutRangeMax[4]: "-1.000000e+00"
    CutRangeMax[5]: "-1.000000e+00"
    CutRangeMax[6]: "-1.000000e+00"
    CutRangeMax[7]: "-1.000000e+00"
    CutRangeMax[8]: "-1.000000e+00"
    CutRangeMax[9]: "-1.000000e+00"
    CutRangeMax[10]: "-1.000000e+00"
    CutRangeMax[11]: "-1.000000e+00"
    CutRangeMax[12]: "-1.000000e+00"
    CutRangeMax[13]: "-1.000000e+00"
    CutRangeMax[14]: "-1.000000e+00"
    CutRangeMax[15]: "-1.000000e+00"
    CutRangeMax[16]: "-1.000000e+00"
VarProp[0]: "FSmart" [Categorisation of cuts]
    VarProp[1]: "FSmart"
    VarProp[2]: "FSmart"
    VarProp[3]: "FSmart"
    VarProp[4]: "FSmart"
    VarProp[5]: "FSmart"
    VarProp[6]: "FSmart"
    VarProp[7]: "FSmart"
    VarProp[8]: "FSmart"
    VarProp[9]: "FSmart"
    VarProp[10]: "FSmart"
    VarProp[11]: "FSmart"
    VarProp[12]: "FSmart"
    VarProp[13]: "FSmart"
    VarProp[14]: "FSmart"
    VarProp[15]: "FSmart"
    VarProp[16]: "FSmart"
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 17
mHH                           mHH                           mHH                           mHH                           GeV                               'F'    [522.839538574,4514.58935547]
j0_pt                         j0_pt                         j0_pt                         j0_pt                         GeV                               'F'    [450.04095459,1981.71484375]
j0_m                          j0_m                          j0_m                          j0_m                          GeV                               'F'    [107.000473022,147.582183838]
j1_pt                         j1_pt                         j1_pt                         j1_pt                         GeV                               'F'    [251.888076782,1911.15478516]
j1_m                          j1_m                          j1_m                          j1_m                          GeV                               'F'    [99.2624664307,136.694396973]
j0_trk0_pt                    j0_trk0_pt                    j0_trk0_pt                    j0_trk0_pt                    GeV                               'F'    [1,8852.76953125]
j0_trk0_m                     j0_trk0_m                     j0_trk0_m                     j0_trk0_m                     GeV                               'F'    [0.702429592609,86.2133636475]
j0_trk0_Mv2                   j0_trk0_Mv2                   j0_trk0_Mv2                   j0_trk0_Mv2                   MV2                               'F'    [-1,0.99999499321]
j0_trk1_pt                    j0_trk1_pt                    j0_trk1_pt                    j0_trk1_pt                    GeV                               'F'    [1,538.708312988]
j0_trk1_m                     j0_trk1_m                     j0_trk1_m                     j0_trk1_m                     GeV                               'F'    [0.328137695789,26.7459888458]
j0_trk1_Mv2                   j0_trk1_Mv2                   j0_trk1_Mv2                   j0_trk1_Mv2                   MV2                               'F'    [-1,0.999999463558]
j1_trk0_pt                    j1_trk0_pt                    j1_trk0_pt                    j1_trk0_pt                    GeV                               'F'    [1,6129.01123047]
j1_trk0_m                     j1_trk0_m                     j1_trk0_m                     j1_trk0_m                     GeV                               'F'    [1,69.9560394287]
j1_trk0_Mv2                   j1_trk0_Mv2                   j1_trk0_Mv2                   j1_trk0_Mv2                   MV2                               'F'    [-1,0.999999046326]
j1_trk1_pt                    j1_trk1_pt                    j1_trk1_pt                    j1_trk1_pt                    GeV                               'F'    [1,409.702423096]
j1_trk1_m                     j1_trk1_m                     j1_trk1_m                     j1_trk1_m                     GeV                               'F'    [0.347260475159,23.9308319092]
j1_trk1_Mv2                   j1_trk1_Mv2                   j1_trk1_Mv2                   j1_trk1_Mv2                   MV2                               'F'    [-1,0.999999523163]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadCuts : public IClassifierReader {

 public:

   // constructor
   ReadCuts( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadCuts" ),
        fNvars( 17 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "mHH", "j0_pt", "j0_m", "j1_pt", "j1_m", "j0_trk0_pt", "j0_trk0_m", "j0_trk0_Mv2", "j0_trk1_pt", "j0_trk1_m", "j0_trk1_Mv2", "j1_trk0_pt", "j1_trk0_m", "j1_trk0_Mv2", "j1_trk1_pt", "j1_trk1_m", "j1_trk1_Mv2" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadCuts() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[17];
   double fVmax[17];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[17];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   // not implemented for class: "ReadCuts"
};
   inline double ReadCuts::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
